/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package realogy.coding.problems
import scala.util.control._

class CodeChallenges {
  def commonSuffix(string1: String, string2: String): Either[String, String] = {

    val formattedString1 = string1.trim.toLowerCase
    val formattedString2 = string2.trim.toLowerCase

    if(formattedString1.isEmpty || formattedString1.isEmpty)
      return Left(s"one of the string sent is empty $string1 or $string2")

    var index = 1
    Breaks.breakable(
      while(index <= Math.min(formattedString1.length, formattedString2.length)) {
        if(!formattedString1.takeRight(index).equalsIgnoreCase(formattedString2.takeRight(index))) Breaks.break
        index += 1
      }
    )

    if(!formattedString1.takeRight(1).equalsIgnoreCase(formattedString2.takeRight(1))) {
      return Left(s"No string found")
    }
    println(s"common suffix ${formattedString1.takeRight(index-1)}")
    Right(formattedString1.takeRight(index-1))
  }
}

object CodeChallenges {
  def apply(): CodeChallenges = new CodeChallenges()
}


